version: '2'
services:
  reportsfactory-app:
    image: reportsfactory
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reportsfactory-postgresql:5432/reportsfactory
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://reportsfactory-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://reportsfactory-elasticsearch:9200
  reportsfactory-postgresql:
    extends:
      file: postgresql.yml
      service: reportsfactory-postgresql
  reportsfactory-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: reportsfactory-elasticsearch
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
